# Generated by Django 5.2.3 on 2025-06-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserv", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "Бронь", "verbose_name_plural": "Бронирования"},
        ),
        migrations.AlterModelOptions(
            name="table",
            options={"verbose_name": "Столик", "verbose_name_plural": "Столики"},
        ),
        migrations.AddField(
            model_name="reservation",
            name="email",
            field=models.EmailField(
                default="admin@example.com", max_length=254, verbose_name="Email"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="name",
            field=models.CharField(default="Admin", max_length=100, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="phone",
            field=models.CharField(
                default="+79000000000", max_length=20, verbose_name="Телефон"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="height",
            field=models.IntegerField(default=50, verbose_name="Высота кнопки"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="shape",
            field=models.CharField(
                choices=[("round", "Круглый"), ("rect", "Прямоугольный")],
                default="rect",
                max_length=10,
                verbose_name="Форма столика",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="width",
            field=models.IntegerField(default=50, verbose_name="Ширина кнопки"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="x",
            field=models.IntegerField(default=0, verbose_name="Координата по X"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="y",
            field=models.IntegerField(default=0, verbose_name="Координата по Y"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reserv.table",
                verbose_name="Столик",
            ),
        ),
    ]
