# Generated by Django 4.2.2 on 2025-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserv", "0003_alter_reservation_options_alter_table_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_duration_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Сколько часов длится одна бронь",
                        verbose_name="Продолжительность брони (часы)",
                    ),
                ),
                (
                    "restaurant_open_time",
                    models.TimeField(
                        default="11:00", verbose_name="Время открытия ресторана"
                    ),
                ),
                (
                    "restaurant_close_time",
                    models.TimeField(
                        default="23:00", verbose_name="Время закрытия ресторана"
                    ),
                ),
                (
                    "last_booking_time",
                    models.TimeField(
                        default="22:00",
                        help_text="До какого времени кухня принимает заказы",
                        verbose_name="Последнее время бронирования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка",
                "verbose_name_plural": "Настройки",
            },
        ),
    ]
