# Generated by Django 4.2.2 on 2025-06-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserv", "0004_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="duration_hours",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Сколько часов длится эта бронь",
                verbose_name="Продолжительность брони (часы)",
            ),
        ),
    ]
