# Generated by Django 4.2.2 on 2025-06-21 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserv", "0005_reservation_duration_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="duration_hours",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Сколько часов длится эта бронь",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Продолжительность брони (часы)",
            ),
        ),
    ]
