# Generated by Django 4.2.2 on 2025-06-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserv", "0006_alter_reservation_duration_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
            ],
            options={
                "verbose_name": "Сообщение обратной связи",
                "verbose_name_plural": "Сообщения обратной связи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="table",
            options={"verbose_name": "Стол", "verbose_name_plural": "Столы"},
        ),
        migrations.AlterField(
            model_name="table",
            name="capacity",
            field=models.PositiveIntegerField(verbose_name="Вместимость"),
        ),
        migrations.AlterField(
            model_name="table",
            name="height",
            field=models.IntegerField(verbose_name="Высота"),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер стола"),
        ),
        migrations.AlterField(
            model_name="table",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Круглый"),
                    ("square", "Квадратный"),
                    ("rectangle", "Прямоугольный"),
                ],
                default="round",
                max_length=20,
                verbose_name="Форма",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="width",
            field=models.IntegerField(verbose_name="Ширина"),
        ),
        migrations.AlterField(
            model_name="table",
            name="x",
            field=models.IntegerField(verbose_name="Позиция X"),
        ),
        migrations.AlterField(
            model_name="table",
            name="y",
            field=models.IntegerField(verbose_name="Позиция Y"),
        ),
    ]
